[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
escrow = "98XjuZZg6GLMZR36ouh2dXtYfDpCp5zLKjtLaSpJGDXj"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
